os: osx

osx_image: xcode7.2

env:
  - NODE_VERSION="4.1"

before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version

install:
  - ./Build\ Scripts/install-dependencies.sh

script:
  - ./Build\ Scripts/backend-test.sh
  - ./Build\ Scripts/ios-test.sh